#!/usr/bin/env bash
# Bash script to install and configure Nginx on Ubuntu 16.04

# Update apt cache
sudo apt update

# Install Nginx
sudo apt install nginx -y

# Allow incoming traffic on port 22 (SSH)
sudo ufw allow 22

# Allow incoming traffic on port 80 (HTTP)
sudo ufw allow 80 

# Enable the firewall and use --force to avoid prompts
sudo ufw --force enable

# Check the status of the firewall
sudo ufw status

# Check the status of the Nginx service 
systemctl status nginx

# Create custom index.html that will be served by Nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart Nginx to load the new index.html
sudo service nginx restart
