#!/usr/bin/env bash
# This script installs and configures Nginx to serve a 'Hello World!' page on port 80.

apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
