#!/usr/bin/env bash
# Bash script to install and configure Nginx on Ubuntu 16.04 with a redirect, custom page, and custom 404

# Update apt cache
apt-get update

# Install Nginx
apt-get install -y nginx

# Create the directory for the custom web pages
mkdir -p /etc/nginx/html

# Create the custom "Hello World!" page
echo "Hello World!" > /etc/nginx/html/index.html

# Create the custom 404 error page
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Configure Nginx with the redirect and custom 404 error page
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/default

# Start Nginx
service nginx start
