#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server

# Update and upgrade apt cache
sudo apt-get update
sudo apt-get -y upgrade

# Install HAproxy
sudo apt-get install -y haproxy

# Enable HAProxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# Backup the original HAProxy configuration
sudo mv /etc/haproxy/haproxy.cfg{,.original}

# Configure HAproxy with the provided configuration
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 531091-web-01 54.90.33.112 check port 80
    server 531091-web-02 23.23.75.134 check port 80
EOT

# Start HAproxy service
sudo service haproxy start
