#!/usr/bin/env bash
# Bash script to generate a MySQL dump and compress it into a tar.gz archive
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
