#!/usr/bin/env bash
# Adjusts Nginx to listen on port 80 and ensures it is not running post-adjustment

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
echo "" | sudo dd status=none of=/run/nginx.pid
sudo systemctl restart nginx
sudo systemctl stop nginx
