#!/usr/bin/env bash
# Change the listening port from 8080 to 80 in the Nginx default site configuration

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
