#!/usr/bin/env bash
# Creates /var/run/myscript.pid with its PID, handles SIGTERM and SIGINT signals, deletes the PID file, and exits gracefully on SIGQUIT or SIGTERM

# Set a variable for the loop
true=0

# Create PID file
echo $BASHPID > /var/run/myscript.pid

# Define signal handling for SIGTERM
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0;' SIGTERM

# Define signal handling for SIGINT
trap 'echo "Y U no love me?!"' SIGINT

# Define signal handling for SIGQUIT
trap 'rm /var/run/myscript.pid; exit 0;' SIGQUIT

# Main loop
while [ $true ]; do
    echo 'To infinity and beyond'
    sleep 2
done
