#!/usr/bin/env bash
# Script to manage manage_my_process

case "$1" in
    start)  # Start
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo 'manage_my_process started'
        ;;
    stop)  # Stop
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        echo 'manage_my_process stopped'
        ;;
    restart)  # Restart
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo 'manage_my_process restarted'
        ;;
    *)  # Invalid argument
        echo 'Usage: manage_my_process {start|stop|restart}'
        ;;
esac
