#!/usr/bin/env bash
# This script displays the username, user ID, and home directory path for each user in /etc/passwd.

while IFS=: read -r username _ userid _ _ home _; do
  echo "$username:$userid:$home"
done < /etc/passwd
