#!/usr/bin/env bash
# This script checks for the existence of a file named "school" and gives information about it.

if [ -e school ]; then
  echo "school file exists"
  
  if [ -s school ]; then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi
  
  if [ -f school ]; then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
