#!/usr/bin/env bash
# Fix Nginx configuration to run as nginx user and listen on port 8080
nginx -s stop
chown nginx:nginx /etc/nginx/nginx.conf
chmod 640 /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;/' /etc/nginx/sites-available/default
sudo -u nginx nginx
