#!/usr/bin/env bash
# Fix Nginx configuration to run as nginx user and listen on port 8080
killall apache2
chown -R nginx:nginx /etc/nginx
chmod -R 777 /etc/nginx
sed -i 's/listen \([0-9]\+\) default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
su nginx -c "service nginx start"
