#!/usr/bin/env bash
# Fix Nginx configuration to run as nginx user and listen on port 8080

sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
useradd -r nginx
sudo -u nginx service nginx restart
